export const ENV = {
  HOME: '',
  RESOURCES_PATH: '',
  SCRIPTS_PATH: '',
  CLIENTS_PATH: '',
  COMPRESSED_PATH: '',
  DIRNAME: '',
  WINE_PATH: '',
  WINE_APPS_PATH: '',
  WINE_SCRIPTS_PATH: '',
  WINE_DOWNLOADS_PATH: '',
  WINE_ASSETS_PATH: '',
  WINE_ENGINES_PATH: '',
  WINE_LIBS_PATH: '',
  WINE_TMP_PATH: ''
};
