# Initializes the environment variables which contains
# the path locations for running wine.
export WINE_BASE_PATH="$HOME/Wine"
export WINE_ENGINES_PATH="$WINE_BASE_PATH/engines"
export WINE_APP_CONTENTS_PATH="$WINE_APP_PATH/Contents"
export WINE_APP_RESOURCES_PATH="$WINE_APP_CONTENTS_PATH/Resources"
export WINE_APP_SHARED_SUPPORT_PATH="$WINE_APP_CONTENTS_PATH/SharedSupport"
export WINE_APP_PREFIX_PATH="$WINE_APP_SHARED_SUPPORT_PATH/prefix"
export WINE_APP_ENGINE_PATH="$WINE_APP_SHARED_SUPPORT_PATH/wine"
export WINE_APP_LOGS_PATH="$WINE_APP_RESOURCES_PATH/logs"
export WINE_APP_BIN_PATH="$WINE_APP_SHARED_SUPPORT_PATH/wine/bin"
export WINE_APP_FRAMEWORKS_PATH="$WINE_APP_CONTENTS_PATH/Frameworks"
export WINE_APP_DRIVE_C_PATH="$WINE_APP_PREFIX_PATH/drive_c"
export PATH="$PATH:$WINE_APP_SCRIPTS_PATH"
